sudo: required

language: generic

env:
- action: noop

services:
- docker

before_install:
# Pull container
- docker pull ubuntu
# TODO: Customize container
- container_id=$(mktemp)
# Run container in detached state
- docker run --privileged --detach ubuntu /sbin/init > "${container_id}"
- cat ${container_id}
