# If language is not specified, Travis-CI will silently default to ruby and crash
# when it tries to run the `rake` command.
language: generic

os: linux

addons:
  apt:
    packages:
      vagrant

before_install:
  - vagrant up

script:
  - true

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
