# Blog post showing how to update gcc version.
# http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
---
language: generic

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.6
    packages:
    - pigz
    - curl
    - zlib1g-dev
    #- libncurses5-dev
    # install toolchains
    #- gcc-5
    #- g++-5
    #- clang-3.6
#    - libbz2-dev

env:
  global:
    - SRC=$HOME/src
    - LOCAL=$HOME/packages
    #- CC=/usr/bin/gcc-5
    #- CXX=/usr/bin/g++-5
    - PATH=${HOME}/bin:$PATH
  matrix:
    #- PROGRAM=samtools
    #  VERSION=$(curl https://api.github.com/repos/samtools/samtools/releases/latest | grep -Pom1 '(?<="name": ").*(?=",)')
#    - PROGRAM=samtools
#      VERSION=1.3.1
#    - PROGRAM=samtools
#      VERSION=1.3
    - PROGRAM=samtools
      VERSION=1.2
#    - PROGRAM=samtools
#      VERSION=1.1
#    - PROGRAM=samtools
#      VERSION=1.0
#    - PROGRAM=samtools
#      VERSION=0.1.20
#    - PROGRAM=samtools
#      VERSION=0.1.19
#    - PROGRAM=samtools
#      VERSION=0.1.18

before_install:
  - mkdir -p ${HOME}/bin
  - ln -s /usr/bin/pigz ${HOME}/bin/gzip
  - ln -s /usr/bin/pigz ${HOME}/bin/gunzip
  - ln -s /usr/bin/pigz ${HOME}/bin/zcat

script:
  - make -j $(grep -c ^processor /proc/cpuinfo) -f samtools.mk $PROGRAM ${PROGRAM^^}_VERSION=$VERSION -d

after_failure:
  - cat /home/travis/src/samtools/1.2/Makefile
