# If language is not specified, Travis-CI will silently default to ruby and crash
# when it tries to run the `rake` command.
language: generic

os: linux


# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
#sudo: required
sudo: false
services: docker


# https://hub.docker.com/_/sentry/
before_install:
  - free -mlt
  - docker run -d --name sentry-redis redis
  - docker run -d --name sentry-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres
  - docker run --rm sentry generate-secret-key
  - docker run -it --rm -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade
  - docker run -d --name my-sentry -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-redis:redis --link sentry-postgres:postgres sentry
  - docker run -d --name sentry-cron -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry run cron
  - docker run -d --name sentry-worker-1 -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry run worker


script:
  - true


#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
