# If language is not specified, Travis-CI will silently default to ruby and crash
# when it tries to run the `rake` command.
language: generic

os: linux

addons:
  apt:
    sources:
      debian-sid
    packages:
      vagrant

before_install:
  # https://askubuntu.com/questions/313920/errors-with-vagrant-and-ubuntu-12-10-with-rvm
  - rvm use system --default
  - vagrant --version
  - vagrant up

script:
  - true

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
