# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

# If language is not specified, Travis-CI will silently default to ruby and crash
# when it tries to run the `rake` command.
language: generic

os: linux

service: docker

before_install:
  # https://askubuntu.com/questions/313920/errors-with-vagrant-and-ubuntu-12-10-with-rvm
  - wget https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
  - sudo dpkg -i vagrant_1.8.4_x86_64.deb
  #- rvm use system --default
  - vagrant --version
  - vagrant up

script:
  - true

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
