---
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.6
    packages:
    - curl
    # install toolchains
    #- gcc-5
    #- g++-5
    #- clang-3.6
#addons:
#  apt:
#  sources:
#    - ubuntu-toolchain-r-test
#  packages:
#    - gcc-4.9
#    - g++-4.9
#    - zlib1g-dev
#    - libbz2-dev
env:
  global:
    - SRC=$HOME/src
    - LOCAL=$HOME/packages
    - CC=/usr/bin/gcc-5
    - CXX=/usr/bin/g++-5
  #matrix:
  #  - FOO=BAR
script:
  - echo ${SRC} ${LOCAL}
  - gcc --version
  - ls -lh /usr/bin | grep gcc
  - make -j $(shell grep -c ^processor /proc/cpuinfo) -f samtools.mk SAMTOOLS_VERSION=1.2
