# https://docs.travis-ci.com/user/languages/java
---
language: java

jdk:
  #- oraclejdk9 oraclejdk9 is not known to travis-ci
  #- openjdk[8-9] is not know to travis-ci
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    #- ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.6
    packages:
    - pigz
    - curl

env:
  global:
    - SRC=$HOME/src
    - LOCAL=$HOME/packages
    - PATH=${HOME}/bin:$PATH
    - PROGRAM=gatk-protected
  matrix:
    - VERSION=3.6
    - VERSION=3.5
    - VERSION=3.4
    - VERSION=3.3
    - VERSION=3.2
    - VERSION=3.1
    - VERSION=3.0

before_install:
  - mkdir -p ${HOME}/bin
  - ln -s /usr/bin/pigz ${HOME}/bin/gzip
  - ln -s /usr/bin/pigz ${HOME}/bin/gunzip
  - ln -s /usr/bin/pigz ${HOME}/bin/zcat

script:
  - make -j $(grep -c ^processor /proc/cpuinfo) $PROGRAM ${PROGRAM^^}_VERSION=$VERSION

#script:
#  - foobar
