---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ROLE="corburn.nginx"

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ansible/ansible'
#    packages:
#      - ansible

before_install:
  # Make sure everything's up to date.
  - sudo add-apt-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq

install:
  # Add ansible.cfg to pick up roles path.
  #- "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - sudo apt-get install -y ansible
  - ls
  - ls -R ./roles/${ROLE}

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i 'localhost,' --syntax-check ./roles/${ROLE}/tests/test.yml
  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i 'localhost,' --connection=local --become --become-user=$USER ./roles/${ROLE}/tests/test.yml
  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i 'localhost,' --connection=local --become ./roles/${ROLE}/tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
