---
- hosts: localhost

  tasks:

    #- name: Install Homebrew
    #  command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Install Neovim Python Module
      pip: name=neomvim state=latest
      ignore_errors: yes

    - name: Install Vim Plugins
      command: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa

    - name: Homebrew Casks
      homebrew_cask: name={{ item }} state=present
      with_items:
        - vagrant
        - vagrant-manager
        - virtualbox

    - name: Update Homebrew
      homebrew: update_homebrew=yes upgrade_all=yes name={{ item }} state=present
      with_items:
        - tmux

