# https://wiki.debian.org/UnattendedUpgrades
---
- name: Install unattended-upgrades along with bsd-mailx for email notification.
  apt:
    name: '{{ item }}'
  with_items:
    - unattended-upgrades
    - bsd-mailx
    #- apt-listchanges
    #- apticron
  become: yes

- name: Configure /etc/apt/apt.conf.d unattended-upgrades
  copy:
    # It is safe to leave backup files in apt.conf.d/ because files
    # ending in '~' are among the files APT ignores by default.
    # http://manpages.ubuntu.com/manpages/wily/man5/apt.conf.5.html
    backup: yes
    dest: '{{ item.dest }}'
    src: '{{ item.src }}'
  with_items:
    #- { src: '10periodic', dest: '/etc/apt/apt.conf.d/10periodic' }
    - { src: '20auto-upgrades', dest: '/etc/apt/apt.conf.d/20auto-upgrades' }
    - { src: '50unattended-upgrades', dest: '/etc/apt/apt.conf.d/50unattended-upgrades' }
  become: yes

# TODO: extract email as a variable
- name: /etc/aliases forward root emails to JasonTravis@nau.edu
  lineinfile:
    backup: yes
    create: yes
    dest: /etc/aliases
    group: root
    line: 'root: JasonTravis@nau.edu'
    mode: 0644
    owner: root
    regexp: '^root:'
  # Execute the command `newaliases` in order to rebuild the indexed file after
  # changing the Postfix alias database.
  notify: newaliases
  become: yes

- name: unattended-upgrades.service is enabled and started
  service: name=unattended-upgrades enabled=yes state=started
  become: yes

# Configure upgrade timing in /etc/apt/apt.conf.d/10periodic
# APT::Periodic::Update-Package-Lists "1";
#APT::Periodic::Download-Upgradeable-Packages "1";
#APT::Periodic::AutocleanInterval "5";
#APT::Periodic::Unattended-Upgrade "1";
