---
# Checking for a new Ubuntu release
# New release '16.04.1 LTS' available.
# Run 'do-release-upgrade' to upgrade to it.
- name: create yes-to-all-prompts configuration
  copy: 
    dest: /etc/apt/apt.conf.d/99corburn.do-release-upgrade
    group: root
    mode: 0644
    owner: root
    src: 99corburn.do-release-upgrade
  become: true

#- name: apt dist-upgrade
#  apt: update_cache=yes upgrade=dist

# TODO: clear old kernels
#- command: uname --kernel-release

- name: do-release-upgrade
  command: do-release-upgrade -f DistUpgradeViewNonInteractive
  become: true

- name: remove yes-to-all-prompts configuration
  file: path=/etc/apt/apt.conf.d/99corburn.do-release-upgrade state=absent
  become: true

# TODO: do-release-upgrade 14.04 -> 16.04 switched the init system from upstart to systemd,
# but left upstart installed. Remove upstart.
# I am not adding this task because I am not certain how check which system is active.
# Removing the wrong one will break the system.

# https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  become: false
